### ISSUE TITLE
Dropbox link dead

### ISSUE THREAD

**Issue by i-guigon** [MAB-Lab/OpenCustomDB#2]
Hello

The Dropbox link provided for downloading your tool is dead.

Could you please fix it?

Thanks in advance.

**Comment by MAB-Lab** [comment]
Hello,

Apologies, and thank you for pointing out the issue. We are experiencing issues with Dropbox currently. We are working on providing a more lasting download link.
Thx

**Comment by i-guigon** [comment]
Hello,

Thank you for your answer.

I was able to download the dropbox archive before the link expired, but I wanted to point it out anyway.

I'm a bit confused since it seemed to me that the scripts in the archive and on GitHub are different, so I'm not sure what scripts I should use.

It's really great to provide an archive with ready-to-use code and databases, but wouldn't it be possible to download the code on GitHub and simply store the databases in the archive? And give the user instructions about either downloading their own databases or using the ones you provide.

Thank you again for your help.

**Comment by bioinformatikLabormedizinUSB** [comment]
I have the same issue.

Where can I download the entire thing to try it out?

Cheers,
Pascal

**Comment by MAB-Lab** [comment]
Hello,

The download link has been updated in the read me. Here, it is: https://api.openprot.org/api/2.0/files/OpenCustomDB/OpenCustomDatabase.zip
